[build]
builder = "NIXPACKS"
buildCommand = "cd ../.. && npm install && npm run build --workspace=web"

[deploy]
startCommand = "npm run start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
