[build]
builder = "NIXPACKS"
buildCommand = "npm install && npm run build --workspace=@website-scraper/web"

[deploy]
startCommand = "cd apps/web && npm run start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
