[build]
builder = "NIXPACKS"
buildCommand = "npm ci && npm run build"

[deploy]
startCommand = "cd apps/web && npm run start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[deploy.watchPatterns]]
include = ["/apps/web/**", "/packages/**", "/package.json", "/package-lock.json", "/turbo.json"]
