#!/bin/bash

# Migration Application Script
# This script helps apply the user_preferences migration to Supabase

set -e

echo "==================================================================="
echo "   Supabase Migration Application Helper"
echo "==================================================================="
echo ""
echo "Migration file: supabase/migrations/20251118120000_create_user_preferences.sql"
echo "Target database: https://xygwtmddeoqjcnvmzwki.supabase.co"
echo ""
echo "STATUS: Table 'user_preferences' does NOT currently exist"
echo ""
echo "-------------------------------------------------------------------"
echo " OPTION 1: Supabase Dashboard SQL Editor (RECOMMENDED)"
echo "-------------------------------------------------------------------"
echo ""
echo "1. Open your browser and navigate to:"
echo "   https://supabase.com/dashboard/project/xygwtmddeoqjcnvmzwki/sql/new"
echo ""
echo "2. Copy the migration SQL:"
echo "   cat supabase/migrations/20251118120000_create_user_preferences.sql | pbcopy"
echo ""
echo "3. Paste the SQL into the SQL Editor and click 'Run'"
echo ""
echo "4. Verify the migration succeeded by running:"
echo "   node check-table.js"
echo ""
echo "-------------------------------------------------------------------"
echo " OPTION 2: Get Direct Database Connection"
echo "-------------------------------------------------------------------"
echo ""
echo "1. Go to: https://supabase.com/dashboard/project/xygwtmddeoqjcnvmzwki/settings/database"
echo ""
echo "2. Copy the 'Connection string' (Direct connection, NOT pooler)"
echo ""
echo "3. Run:"
echo "   psql '<connection_string>' -f supabase/migrations/20251118120000_create_user_preferences.sql"
echo ""
echo "4. Verify the migration succeeded by running:"
echo "   node check-table.js"
echo ""
echo "-------------------------------------------------------------------"
echo " After applying the migration, run this to verify:"
echo "-------------------------------------------------------------------"
echo ""
echo "   node check-table.js"
echo ""
echo "==================================================================="
