[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = [
  "npm run build --workspace=@website-scraper/api",
  "npm run build --workspace=web"
]

[start]
cmd = "npm run start:prod"
