[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

# Note: No [start] command here - each Railway service configures its own start command in the dashboard
# API service: cd apps/api && npm run start:prod
# Web service: cd apps/web && npm run start
