[build]
builder = "NIXPACKS"
buildCommand = "npm install && npm run build --workspace=@website-scraper/api"

[deploy]
startCommand = "cd apps/api && npm run start:prod"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
