[build]
builder = "NIXPACKS"
buildCommand = "npm ci && npm run build"

[deploy]
startCommand = "cd apps/api && npm run start:prod"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[deploy.watchPatterns]]
include = ["/apps/api/**", "/packages/**", "/package.json", "/package-lock.json", "/turbo.json"]
